[tool.poetry]
name = "poetry-demo"
version = "1.0.0"
description = ""
authors = ["Keisuke69 <providence000@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
